{% set name = "sceptre-cmd-resolver" %}
{% set version = "1.2.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sceptre-cmd-resolver-{{ version }}.tar.gz
  sha256: ff83298ae86a51df150de28cd17c3754c64aad2bc7813c3095cc5cfc7fad89f1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner >=3
    - python >=3.6
  run:
    - packaging ==16.8
    - python >=3.6

test:
  imports:
    - resolver
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Sceptre/sceptre-resolver-cmd
  summary: Sceptre resolver to execute generic shell commands
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - admax18
    - mxr-conda
